# Generated by Django 3.1.6 on 2021-03-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_tender_api', '0004_auto_20210314_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenders',
            name='availibility',
            field=models.CharField(choices=[('inactive', 'Inactive'), ('active', 'Active')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='tenders',
            name='category',
            field=models.CharField(choices=[('telecom', 'Telecom'), ('medical', 'Medical'), ('electrical', 'Electrical'), ('oil and gas', 'Oil and Gas'), ('others', 'Others'), ('it', 'IT'), ('construction', 'Construction')], default='Construction', max_length=100),
        ),
    ]
